### PR TITLE
Extend Authorization docs' table of contents with subsections for specific requests

### PR DESCRIPTION
**Pull request by mjlumetta**
### Description

refines Authorization docs headings and table of contents based on usability research. for [API-5500](https://vajira.max.gov/browse/API-5500).

### Process

- [X] Tests added or updated for change
- [n/a] Docs updated
  - [n/a] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [n/a] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [X] Accessibility concerns have been considered and addressed
  
  - [X] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### CODE REVIEW

**Comment by mjlumetta** [comment]
@darduda if you have a few minutes to review the tweaks in the heading wording and structure, that'd be great. hope that won't take too long since they're pretty minor.

**Review by ediiotero — APPROVED** [review]
LGTM!

**Review by gileswells — APPROVED** [review]
LGTM

**Comment by darduda** [comment]
This looks good to me. No suggestions for these changes

**Pull request merged**
