### PR TITLE
Update configuration to use va.gov instead of vets.gov

### PR DESCRIPTION
**Pull request by edpaget**
Noticed these aren't pointing to va.gov :exclamation:

### CODE REVIEW

**Comment by kalilsn** [comment]
Few more of these if you have a sec:
- 2 in the [readme](https://github.com/department-of-veterans-affairs/developer-portal/blob/c0452d7449f02153ce2b5fab2ee6da01abee4034/README.md)
- https://github.com/department-of-veterans-affairs/developer-portal/blob/d0811307df9f25972db70c042759637fdc67d3ff/src/content/goLive.mdx#L42
- https://github.com/department-of-veterans-affairs/developer-portal/blob/d0811307df9f25972db70c042759637fdc67d3ff/src/content/apiDocs/benefitsOverview.mdx#L52

**Comment by edpaget** [comment]
That regression test failure looks like it might just be a different between the fonts on my machine and how it's being rendered on Jenkins :(

**Comment by kalilsn** [comment]
@edpaget did you run those updates in the docker container?

**Comment by edpaget** [comment]
Oh duh I'll do that @kalilsn

**Pull request merged**
