### PR TITLE
Release notes readme ian h

### PR DESCRIPTION
**Pull request by hubgitian**
Adding intro text and graphic of examples

### CODE REVIEW

**Comment by Eallan919** [comment]
OHHH!!! @hubgitian you outdid yourself with the flags!!! I am loving it! 

Are you able to tag Jeff, Derek, and Ryan L? I cannot for some reason?!?!?!

**Comment by hubgitian** [comment]
@Eallan919 tagged Jeff, Derek, and Ryan :)

**Comment by hubgitian** [comment]
> Er, I think I did this wrong. I made little changes to your branch instead of requesting them, should show as another commit. LGTM otherwise!

No worries, all solid changes! Thanks for the review 👍

**Comment by rtravitz** [comment]
Closing as part of developer-portal cleanup. Release notes are going to need a larger visit when consumer and provider experience teams grow soon.

**Pull request closed without merging**
