### PR TITLE
Api 9027/onboarding docs punchlist

### PR DESCRIPTION
**Pull request by wwanamaker**
### Description

This PR addresses numerous typos, incorrect case, boldness, and page link issues within the new consumer docs pages. None of this will actually be accessible until the consumer docs flag is switched which is planned for later this week.

### Process

I do not believe these changes impact any of the test cases.

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

Almost everything was just very simple text content changes and href links to new pages. I don't think this work should impact anything else, but would appreciate review!

### CODE REVIEW

**Review by johanna-adhoc — APPROVED** [review]
LGTM. I also fixed some lint errors

**Review by johanna-adhoc — APPROVED** [review]

**Review by mjlumetta — COMMENTED** [review]
one suggested change but yeah looks good

**Review by bradenshipley — APPROVED** [review]
LGTM

**Review by mjlumetta — APPROVED** [review]
✨

**Review by johanna-adhoc — APPROVED** [review]
Feel free to merge!

**Pull request merged**
