### PR TITLE
API: 2935 - Remove HoverImage Component

### PR DESCRIPTION
**Pull request by TS000**
### Description
Jira ticket [here](https://vajira.max.gov/browse/API-2935)
Removed HoverImage and replaced it's functionality with CSS.

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback

Feedback welcome.

### CODE REVIEW

**Review by anthony-kopczyk — DISMISSED** [review]
This looks good to me, but I did have some thoughts that maybe we could further improve this in other tickets. I'm unsure if these suggestion are worth pursuing though.

When changing the size of the page the new div snaps to different sizes where the original slowly gets smaller as you change the screen size. I don't think this is necessarily something to block the PR though.

The other thought, and this is how it works in prod already, so again nothing to block this PR, is that the other Digital media each have a play button after the link. This link, and 'play button', has no function and does not get read out loud by a screen reader (using NVDA on Chrome Windows). I'm not sure if this could be confusing, since it doesn't quite match the pattern of the other Digital media links.

**Comment by TS000** [comment]
I went through and checked the most used viewports to make sure there weren't any bad jumps.

**Comment by johanna-adhoc** [comment]
I think this class name should be something like "hover-image-videoplayer" given that the image to be displayed is actually really specific and not generic and totally reusable

**Review by anthony-kopczyk — APPROVED** [review]
Looks good

**Review by johanna-adhoc — APPROVED** [review]
👍

**Pull request merged**
