### PR TITLE
Adding metadata end points for hlr and appeals status

### PR DESCRIPTION
**Pull request by bastosmichael**
### Description
For ticket https://vajira.max.gov/browse/API-1451

Discovered that the reason for decision review defaulting to v0 was because it was missing a metadata end point.

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
- [ ] Accessibility concerns have been considered and addressed

### CODE REVIEW

**Comment by bastosmichael** [comment]
Thanks, still have to wait for this PR https://github.com/department-of-veterans-affairs/vets-api/pull/4540 to get approved and merge first before I can merge this one but tested both against one another locally and it seemed just fine.

**Comment by rtravitz** [comment]
Snapshots are failing because the timer was hit for a deactivation of an API, which makes the end result look different from the PNGs currently on master. These will be fixed shortly in #383.

**Comment by rtravitz** [comment]
@bastosmichael Looks like the other PR you referenced is merged. Is this one okay to go in?

**Comment by bastosmichael** [comment]
I wanted to test things first and I found an issue with a devops change I needed to make so will put another PR out before we merge this.

**Comment by bastosmichael** [comment]
Here is the devops change for this https://github.com/department-of-veterans-affairs/devops/pull/7324

**Pull request merged**
