### PR TITLE
Have Jenkinsfile use vagov swarm node

### PR DESCRIPTION
**Pull request by njdister**
Ref: department-of-veterans-affairs/vets.gov-team#18570

### CODE REVIEW

**Comment by njdister** [comment]
Error when running in Jenkins VAEC:
http://jenkins.vetsgov-internal/job/testing/job/developer-site/job/njdister-jenkinsfile-vagov/1/console

```
[91mWarning: apt-key output should not be parsed (stdout is not a terminal)
[0m[91mgpg: no valid OpenPGP data found.
[0mThe command '/bin/sh -c apt-get update && apt-get install -y wget --no-install-recommends     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'     && apt-get update     && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont       --no-install-recommends     && rm -rf /var/lib/apt/lists/*     && apt-get purge --auto-remove -y curl     && rm -rf /src/*.deb' returned a non-zero code: 2
```

**Comment by omgitsbillryan** [comment]
Is there no strategy yet for getting the VA certs installed into the docker images used for building?

**Comment by njdister** [comment]
> Is there no strategy yet for getting the VA certs installed into the docker images used for building?

I don't think there has been a final decision on whether it's acceptable to upload docker images with private certs to dockerhub, or whether these images should live in ECR.

**Comment by omgitsbillryan** [comment]
My strategy (probably not a good one), was to add a stage in the jenkinsfile to copy the VA certs on the local swarm machine (i forget the location) into the jenkins workspace. I would then modify the respective `Dockerfile` to copy said certs before anything else, e.g.

```
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY ./*.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
```

**Comment by njdister** [comment]
> My strategy (probably not a good one), was to add a stage in the jenkinsfile to copy the VA certs on the local swarm machine (i forget the location) into the jenkins workspace. I would then modify the respective `Dockerfile` to copy said certs before anything else, e.g.
> 
> ```
> RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
> COPY ./*.crt /usr/local/share/ca-certificates/
> RUN update-ca-certificates
> ```

When you say modify the Dockerfile, do you mean on the fly for that build, or permanently?  We need to preserve the original Dockerfile for those working locally, particularly with for the public/open source repos.

**Comment by omgitsbillryan** [comment]
I think I created a separate `Dockerfile`, like `Dockerfile.jenkins` - which loops back to the fact that it's kind of not a great strategy to begin with.

**Comment by rtravitz** [comment]
Hey @omgitsbillryan, I'm cleaning up old PRs. Is this still needed, or can I close it?

**Comment by omgitsbillryan** [comment]
👍 to closing. It's nearly 1 year old 😲

**Pull request closed without merging**
