### PR TITLE
Override 16px base font size from formation

### PR DESCRIPTION
**Pull request by kalilsn**
https://github.com/department-of-veterans-affairs/vets-contrib/issues/2893

### CODE REVIEW

**Comment by mjlumetta** [comment]
@kalilsn is there any particular rationale for doing this?

**Comment by kalilsn** [comment]
>@kalilsn is there any particular rationale for making this change?

There's a weak one: the current site uses 17px because that's what's in USWDS. I don't feel very strongly about it either way, so I'm happy to drop this if others feel that's what's best.

**Comment by mjlumetta** [comment]
@kalilsn i would prefer not to in general, because it's a 1 pixel difference and i would prefer to keep following the principle that we don't override the design system defaults unless we have a good UI/UX reason to do so. i can see one short-term benefit to this, though, which is that it would substantially reduce noise in the visual regression tests when we're trying to figure out what's okay and what we still need to fix.

**Comment by kalilsn** [comment]
> @kalilsn i would prefer not to in general, because it's a 1 pixel difference and i would prefer to keep following the principle that we don't override the design system defaults unless we have a good UI/UX reason to do so. i can see one short-term benefit to this, though, which is that it would substantially reduce noise in the visual regression tests when we're trying to figure out what's okay and what we still need to fix.

Cool, I agree 100%. Given that, do you think I should make the api status link 16px as well?

**Comment by mjlumetta** [comment]
@kalilsn yeah, definitely. i think that'd be an appropriate thing to do here

**Pull request merged**
