### PR TITLE
[API-9603] Address Validation FAQ

### PR DESCRIPTION
**Pull request by Cgfor3**
### Description

Remove entire question and answer section for Address Validation FAQ
https://vajira.max.gov/browse/API-9603

### Process
  - [x] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### Requested feedback
N/A

### CODE REVIEW

**Review by gileswells — DISMISSED** [review]
LGTM just need to update the visual regressions

**Review by stiehlrod — APPROVED** [review]
LGTM

**Comment by Cgfor3** [comment]
Any idea why the visual regression tests would pass locally then fail in CI?

**Comment by Cgfor3** [comment]
Was able to resolve the snapshot issues I was having. Ready for approval

**Review by TS000 — APPROVED** [review]
Looks great! 🎸

**Pull request merged**
