### PR TITLE
Update claims attribute to use new docserver s3 bucket

### PR DESCRIPTION
**Pull request by RockslideJr**
### Description
[API-5444](https://vajira.max.gov/browse/API-5444)

This PR switches claims attributes OAS over from the docserver route to the docserver s3 bucket route.

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### CODE REVIEW

**Review by christineyost — APPROVED** [review]
LGTM 🎉

**Review by michaelkimball — CHANGES_REQUESTED** [review]
image
I don't think this is updated all the way

**Comment by RockslideJr** [comment]
@michaelkimball that screenshot is not of the claims attributes documentation. I don't think we're making any changes to benefits claims

**Review by michaelkimball — APPROVED** [review]

**Comment by michaelkimball** [comment]
> 
> 
> @michaelkimball that screenshot is not of the claims attributes documentation. I don't think we're making any changes to benefits claims

You are 100% correct. Whoops!

**Pull request merged**
