### PR TITLE
Flex content to always place footer at the bottom of the viewport at …

### PR DESCRIPTION
**Pull request by rtravitz**
Fixes [#1908](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1908)

* Use flexbox to always place the footer at the bottom of the page.
* Handle short pages where the content does not take up the whole viewport by setting a minimum height of 100vh.

### CODE REVIEW

**Comment by rtravitz** [comment]
Does anyone have a good way to test changes in IE11? Spin up a windows environment in VirtualBox? I'm concerned about a pretty well-known min-height/flexbox bug in that browser.

**Comment by nfasulo** [comment]
I have a laptop with Windows on it if you want me to give the test build of the developer portal a spin IE 11. But if you are looking for a solution for checking IE 11 while you are developing, VirtualBox sounds like a good bet. It used to be possible to use Azure RemoteApp to run a copy of IE remotely, but it looks to me like that has been killed.

**Comment by dvogel** [comment]
> @kalilsn @dvogel @nfasulo Does anyone have a good way to test changes in IE11? Spin up a windows environment in VirtualBox? I'm concerned about a pretty well-known min-height/flexbox bug in that browser.

If it's something you're comfortable fixing post-merge, I believe we can use SauceLabs for dev-developer.va.gov. I don't remember the details -- like if there's a special account to use -- but the VA.gov team was helpful when I needed it.

**Comment by rtravitz** [comment]
@nfasulo kindly tested this in IE and the min-height bug is indeed happening. So I'm going to set up VirtualBox for dev purposes. 

@dvogel That is great to know. Thank you!

**Comment by rtravitz** [comment]
Alright folks, set up VirtualBox and made changes to fix IE, so this is ready for review. It's failing the CI check currently because of visual regression tests, which I'll update. But feel free to start giving feedback!

**Comment by nfasulo** [comment]
The OAuth page changing from mobile layout to regular is weird. Not suggesting you need to do anything, just noting the oddity.

**Comment by rtravitz** [comment]
> Visual regression testing failed. Review these diffs and then update the snapshots. 
> 
> [renders-oauth-properly-3-diff.png](https://s3-us-gov-west-1.amazonaws.com/developer-portal-screenshots/ade290e70aa2b980192e777d03c0e3f0a45c5269/visual-regression-test-ts-visual-regression-test-renders-oauth-properly-3-diff.png)

Except I reran this locally and everything is fine. Going to kick it off in Jenkins again.

**Comment by rtravitz** [comment]
Any ideas, team? I rebuilt the visual test docker image. All of the tests pass locally. Working tree is clean with nothing to commit. Everything up to date with the remote.

**Pull request merged**
