### PR TITLE
Adding a v2 to dev swagger

### PR DESCRIPTION
**Pull request by mviterna**
### Description
This is the front end change we need to align with this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/7492/files

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### CODE REVIEW

**Review by mjlumetta — COMMENTED** [review]
lgtm in terms of code change, but there are 2 issues that I think need to be answered.

1. the documentation route for v2 isn't up, so the docs don't render. that's fine as long as you're aware of it and are going to release the docs later.
2. since Team Quokka is currently converting OpenAPI specs to be served from the doc server, you may want to work with them to confirm it's okay to change this back to use the API directly. they are currently working on supporting metadata in the doc server (or they may be done, not sure). I'm sure it's probably fine to convert back to this setup so you can test, but I would check with them to be sure. @department-of-veterans-affairs/lighthouse-quokka

**Comment by mviterna** [comment]
> lgtm in terms of code change, but there are 2 issues that I think need to be answered.
> 
> 1. the documentation route for v2 isn't up, so the docs don't render. that's fine as long as you're aware of it and are going to release the docs later.
> 2. since Team Quokka is currently converting OpenAPI specs to be served from the doc server, you may want to work with them to confirm it's okay to change this back to use the API directly. they are currently working on supporting metadata in the doc server (or they may be done, not sure). I'm sure it's probably fine to convert back to this setup so you can test, but I would check with them to be sure. @department-of-veterans-affairs/lighthouse-quokka

Interesting on the route...I'll have to double check that. We definitely want them to render in dev. As far as the OpenAPI from the dev server, we understand there will bee some rework and we do want to move away from swagger blocks and go with rswag, but it was not feasible to do that in this sprint.

**Comment by mviterna** [comment]
> > lgtm in terms of code change, but there are 2 issues that I think need to be answered.
> > 
> > 1. the documentation route for v2 isn't up, so the docs don't render. that's fine as long as you're aware of it and are going to release the docs later.
> > 2. since Team Quokka is currently converting OpenAPI specs to be served from the doc server, you may want to work with them to confirm it's okay to change this back to use the API directly. they are currently working on supporting metadata in the doc server (or they may be done, not sure). I'm sure it's probably fine to convert back to this setup so you can test, but I would check with them to be sure. @department-of-veterans-affairs/lighthouse-quokka
> 
> Interesting on the route...I'll have to double check that. We definitely want them to render in dev. As far as the OpenAPI from the dev server, we understand there will bee some rework and we do want to move away from swagger blocks and go with rswag, but it was not feasible to do that in this sprint.

Ok, yeah so https://vajira.max.gov/browse/API-8767 has not been implemented yet. We will stand by on this ticket until the other work is complete.

**Comment by dsteeve** [comment]
> > > lgtm in terms of code change, but there are 2 issues that I think need to be answered.
> > > 
> > > 1. the documentation route for v2 isn't up, so the docs don't render. that's fine as long as you're aware of it and are going to release the docs later.
> > > 2. since Team Quokka is currently converting OpenAPI specs to be served from the doc server, you may want to work with them to confirm it's okay to change this back to use the API directly. they are currently working on supporting metadata in the doc server (or they may be done, not sure). I'm sure it's probably fine to convert back to this setup so you can test, but I would check with them to be sure. @department-of-veterans-affairs/lighthouse-quokka
> > 
> > 
> > Interesting on the route...I'll have to double check that. We definitely want them to render in dev. As far as the OpenAPI from the dev server, we understand there will bee some rework and we do want to move away from swagger blocks and go with rswag, but it was not feasible to do that in this sprint.
> 
> Ok, yeah so https://vajira.max.gov/browse/API-8767 has not been implemented yet. We will stand by on this ticket until the other work is complete.

yeah, we should probably have a conversation on the short term and mid term plan here.

**Review by dsteeve — APPROVED** [review]
Will approve this since the metadata URL changes that were mentioned in the conversations is not completely ready yet.  We will create a ticket to move this back to using $Host/internal/docs/... once that work is completed.

**Pull request merged**
