### PR TITLE
Create whats-new.mdx

### PR DESCRIPTION
**Pull request by jeff2d2**
Creates a new `src/contents/whats-new` directory and `whats-new.mdx` file for holding what will be shown in the new `What's New` main nav page. This holds the current collection we have for VA Press Releases, News, and Media.

[Figma mockup here](https://www.figma.com/file/Nuojmnzapx5BitKDCePot78g/Release-Notes?node-id=5336%3A2)

### CODE REVIEW

**Comment by jeff2d2** [comment]
@juliaelman Do you have any other VA Press Releases, News, or Media that should be included on this page besides these?

**Comment by juliaelman** [comment]
@jeff2d2 nope!

**Comment by jeff2d2** [comment]
@nfasulo Is this good to go, keeping in mind we want the left nav to jump to the individual sections, or do we need some html tags or something added in here?

**Comment by nfasulo** [comment]
> @nfasulo Is this good to go, keeping in mind we want the left nav to jump to the individual sections, or do we need some html tags or something added in here?

@jeff2d2 yes, we do have to add html tags into the mdx to target for anchors. It's not a big deal though.

I actually already split the `release-notes.mdx` into separate files (local only for now), so I will see if there are changes to the content here before I open my What's New PR.

**Comment by jeff2d2** [comment]
@nfasulo perfect! I was attempting to save you that step, but I should've figured you were on it. Slay away good sir!

**Pull request closed without merging**
