### PR TITLE
Release notes - Turning back on name validation

### PR DESCRIPTION
**Pull request by anaricci-va**
These notes should not be released until Monday, 05/24/2021.

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### CODE REVIEW

**Comment by anaricci-va** [comment]
This pull request is tied to https://github.com/department-of-veterans-affairs/vets-api/pull/6986

**Review by gileswells — DISMISSED** [review]
For when it's ready to get pushed live this LGTM.

**Review by darduda — DISMISSED** [review]
Approved, with a few minor edits below: 

(v1) We have turned back on the new Veteran first and last name field validations described in the May 17 release notes. In addition to these new validations, we will allow spaces in these fields, including leading and trailing spaces (white space). [#6986](https://github.com/department-of-veterans-affairs/vets-api/pull/6986)

**Review by gileswells — APPROVED** [review]
LGTM with the change

**Pull request merged**
