### PR TITLE
Update all pages to use new card links

### PR DESCRIPTION
**Pull request by mjlumetta**
### Description

completes [API-8638](https://vajira.max.gov/browse/API-8638). gonna fill this out later this is just for visibility

### Process

- [ ] Tests added or updated for change
- [ ] Docs updated
  - [ ] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
  - [ ] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [ ] Accessibility concerns have been considered and addressed
  
  - [ ] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

### CODE REVIEW

**Review by brentschneider — APPROVED** [review]
The cards and adjusted content width look fabulous across the site!

**Comment by johanna-adhoc** [comment]
LGTM

**Review by johanna-adhoc — APPROVED** [review]
LGTM

**Comment by mjlumetta** [comment]
not merging yet so it can go out with consumer docs release

**Pull request merged**
