### PR TITLE
Enable claims attributes docs in production

### PR DESCRIPTION
**Pull request by hinzed1127**
### Description

This enables claims attributes documentation in prod, per https://vajira.max.gov/browse/API-5062

### CODE REVIEW

**Review by charleystran — APPROVED** [review]
Code is good to me once the build is fixed. Not sure what is causing the issue, but Okapi and jump in and help.

**Review by SlakrHakr — APPROVED** [review]

**Review by SlakrHakr — APPROVED** [review]

**Comment by gileswells** [comment]
@hinzed1127 @SlakrHakr: I think the easiest way to resolve these conflicts is to do a hard reset back to `52a8e2b` with `git reset --hard 52a8e2b` and then merge in master before a final re-run of the visual regressions. Those specific PRs that are causing the package conflicts were mine and are wholly replaced by what's now in master.

**Comment by SlakrHakr** [comment]
> @hinzed1127 @SlakrHakr: I think the easiest way to resolve these conflicts is to do a hard reset back to `52a8e2b` with `git reset --hard 52a8e2b` and then merge in master before a final re-run of the visual regressions. Those specific PRs that are causing the package conflicts were mine and are wholly replaced by what's now in master.

@gileswells: Ok, I think I did what you suggested. Hopefully this build passes, and then it looks like it'll need a quick approval.

**Review by gileswells — APPROVED** [review]
LGTM this'll be the next to merge in my list. Hopefully deployed tomorrow morning.

**Pull request merged**
