### PR TITLE
API-3755: Added unit test to CrisisPanelInfo component.

### PR DESCRIPTION
**Pull request by johanna-adhoc**
### [API-3755](https://vajira.max.gov/browse/API-3755)
 Create unit test for CrisisPanelInfo component. Run jest coverage in test file to ensure 95% coverage.

### Process
- [X] Tests added or updated for change
- [N/A] Docs updated
- [N/A] If you have made structural changes to the site, the [Developer Portal Content Types](https://community.max.gov/x/qUwOg) docs have been updated
- [N/A] If you have made/confirmed any decisions about user interactions and accessibility, the [Accessible Component Design](https://community.max.gov/x/xS8mgg) docs have been updated
- [N/A] Accessibility concerns have been considered and addressed
- [N/A] If you've made any UI changes, you've run an axe check using the axe browser extension that reported no new issues

Screen Shot 2020-12-02 at 12 28 05 PM

### CODE REVIEW

**Review by TS000 — APPROVED** [review]
Looks great 🚀

**Review by anthony-kopczyk — APPROVED** [review]
This looks good to me.

One note, the react testing library docs seem to prefer using `getByRole` where possible rather than `querySelector`, but it's not very explicit about it. This tests looks good, and we can merge.

https://testing-library.com/docs/guide-which-query/

**Review by TS000 — APPROVED** [review]
Looks great!

**Review by anthony-kopczyk — APPROVED** [review]
Looks good to me!

**Pull request merged**
