### PR TITLE
Add facilities csv fix release note

### PR DESCRIPTION
**Pull request by rtravitz**
Finishes [#1885](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1885)

### CODE REVIEW

**Comment by jeff2d2** [comment]
@rtravitz Could you be a bit more specific? I think it would be helpful to add in that it was a `500` error, and that it was affecting the `/facilities/all` bulk download endpoint.

**Comment by rtravitz** [comment]
@jeff2d2 Definitely, I just took the current language from [the top of the issue](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1885).

How about: Fix an error where the `/facilities/all` endpoint returned a 500 status code when a user requested `text/csv`. [#2974](https://github.com/department-of-veterans-affairs/vets-api/pull/2974)

**Comment by jeff2d2** [comment]
Perfection!

**Comment by rtravitz** [comment]
Ended up tweaking the format slightly to match up with other release notes in that section. It looked a bit odd to have that one title go on for so long, so I moved the bulk of the updated text to a bullet point.

**Pull request merged**
